install.packages("here")
install.packages("data.table")
install.packages("dplyr")
install.packages("tidyverse")
install.packages("sf")
install.packages("foreign")
install.packages("stringr")
install.packages("patchwork")
install.packages("scales")

library(foreign)
library(sf)
library(dplyr)
library(tidyverse)
library(stringr)
library(ggplot2)
library(here)
library(patchwork)
library(scales)

# Disable scientific notation
options(scipen = 999)

source("C:/Users/white/Downloads/new_project_scaffold.R")
create_project("C:/Users/white/OneDrive/Documents/buyouts_proj")
